// Generated by CoffeeScript 1.9.3
(function() {
  var executeOnLoad, isInDOMTree;

  console.log('ZEFR PR HELPER ACTIVE');

  isInDOMTree = function() {
    if (document.getElementById('pull_request_body') !== null) {
      return true;
    } else {
      return false;
    }
  };

  executeOnLoad = function(func) {
    if (isInDOMTree()) {
      func();
    } else {
      setTimeout((function() {
        executeOnLoad(func);
      }), 100);
    }
  };

  executeOnLoad(function() {
    var element;
    element = document.getElementById('pull_request_body');
    if (element.value === null || element.value === void 0 || element.value === '') {
      return element.value = '### Summary\n\n### Bug Fixes/New Features\n\n### How to Verify\n\n### Side Effects\n\n### Resolves\n\n### Tests\n\n### Code Reviewer(s)';
    }
  });

}).call(this);
